version: '3'
services:
  product:
    image: ecomm/product
    build: product
    entrypoint: 'npm run start:dev'
    volumes:
      - ./product:/app
    ports:
      - 3000:3000
  account:
    image: ecomm/account
    build: account
    entrypoint: 'npm run start:dev'
    volumes:
      - ./account:/app
    ports:
      - 3001:3000
  account_db:
    image: mongo
    container_name: account_db 
    environment:
      - MONGO_INITDB_DATABASE=accounts
      - MONGO_INITDB_ROOT_USERNAME=vanderleia
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
    - 27017:27017
