version: '3'
services:
  product:
    image: ecomm/product
    build: product
  account:
    image: ecomm/account
    build: account
    volumes:
      - ./account:/app
  db:
    image: mongo
    container_name: mongodb 
    environment:
      - MONGO_INITDB_DATABASE=accounts
      - MONGO_INITDB_ROOT_USERNAME=vanderleia
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
    - 27017:27017
